### ISSUE TITLE
Resizing too small causes crash

### ISSUE THREAD

**Issue by LumenTeun** [munsking/cliReddit#10]
curses can't change the colors of the subreddit section if there aren't enough columns. This is because the x values are hardcoded at lines 272-274.
Fix by replacing the values with variables and later using a [curses.is_term_resized()](https://docs.python.org/3.4/library/curses.html#curses.is_term_resized) in the event loop to change these depending on the terminal size.

**Comment by LumenTeun** [comment]
This was fixed with by @f3tus in 091bad13e110c7668ca68c60beb3b3be4f528890

**Comment by f3tus** [comment]
nope. not completely. If the windows is smalll before the program starts, it still breaks because "x values are hardcoded" at lines 410-416.

**Comment by LumenTeun** [comment]
True, but the title of this issue is "Resizing[...]" not "Starting small", so we'll take this as a win ;)

**Comment by f3tus** [comment]
haha! very well.

**Comment by LumenTeun** [comment]
I'll try to softcode the menu colors to fix that as well though. Thanks for the reminder :)
