### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by LumenTeun** [munsking/cliReddit#9]
Figure out and use curses windows so that we don't have to keep redrawing the menus etc.
Maybe add a window for each separate column?

**Comment by f3tus** [comment]
Sup! Cool program. I've added pads instead of windows. They can be larger than the terminal, and can therefore be used to scroll.

**Comment by LumenTeun** [comment]
@f3tus Sounds great! Make a [pull request](https://help.github.com/articles/using-pull-requests/) and I'll review the code :)
Oh, and it looks like you joined GitHub yesterday, so feel free to ask if you have any questions, and welcome!
